FROM python:3.12-slim

WORKDIR /code

COPY requirements.worker.txt .
RUN pip install --no-cache-dir -r requirements.worker.txt

COPY . .

EXPOSE 8001

CMD ["uvicorn", "worker_api:app", "--host", "0.0.0.0", "--port", "8001"]