site_name: ContraDito
site_description: Documentação do projeto da disciplina de MDS

theme:
  name: material
  palette:
    primary: custom # Cor da barra superior 
    accent: custom  # Cor dos botões e links
  features:
    - navigation.tabs # Isso aqui transforma o menu lateral em abas superiores!
    - navigation.top  # Adiciona um botão de "voltar ao topo"

nav:
  - Home: index.md
  - Transparência e LGPD: lgpd.md
  - Arquitetura: arquitetura.md
  - Como Calculamos o Score: calculo-score.md
  - Como executar o projeto?: execucao.md
  - Sprints:
      - Sprint 0: sprints/sprint-0.md
  - API: api.md

extra_css:
  - stylesheets/extra.css
